
version: 2.1

orbs:

  python: circleci/python@1.5.0


jobs:
  lintng-and-test:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest

  build-and-deploy:
    machine: true

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: docker build -t oc_lettings:$CIRCLE_SHA1 .
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push oc_lettings:$CIRCLE_SHA1


        # Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - lintng-and-test
      - build-and-deploy:
          requires:
            - lintng-and-test
