
version: 2.1

orbs:

  python: circleci/python@1.5.0


jobs:
  lintng-and-tests:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest

  build:
    machine: true
    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Build image and push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker build -t orphee1980/repo_letting:$CIRCLE_SHA1 .
            docker push orphee1980/repo_letting:$CIRCLE_SHA1
  deploy:
    machine: true
    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker tag orphee1980/repo_letting:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  sample:
    jobs:
      - lintng-and-tests
      - build:
          requires:
            - lintng-and-tests
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - lintng-and-tests
            - build
          filters:
            branches:
              only: master
